<h2 style="color: #fff;">
    Modelos de Classificação
</h2>

In [26]:
import pandas as pd

uri = 'https://raw.githubusercontent.com/alura-cursos/ML_Classificacao_por_tras_dos_panos/main/Dados/Customer-Churn.csv'
data = pd.read_csv(uri)

data.head()

Maior65Anos Conjuge Dependentes  MesesDeContrato TelefoneFixo  \
0            0     Sim         Nao                1          Nao   
1            0     Nao         Nao               34          Sim   
2            0     Nao         Nao                2          Sim   
3            0     Nao         Nao               45          Nao   
4            0     Nao         Nao                2          Sim   

  VariasLinhasTelefonicas ServicoDeInternet SegurancaOnline BackupOnline  \
0    SemServicoTelefonico               DSL             Nao          Sim   
1                     Nao               DSL             Sim          Nao   
2                     Nao               DSL             Sim          Sim   
3    SemServicoTelefonico               DSL             Sim          Nao   
4                     Nao       FibraOptica             Nao          Nao   

  SeguroNoDispositivo SuporteTecnico TVaCabo StreamingDeFilmes TipoDeContrato  \
0                 Nao            Nao     Nao               Nao    Mensalmente   
1                 Sim            Nao     Nao               Nao          UmAno   
2                 Nao            Nao     Nao               Nao    Mensalmente   
3                 Sim            Sim     Nao               Nao          UmAno   
4                 Nao            Nao     Nao               Nao    Mensalmente   

  PagamentoOnline FormaDePagamento  ContaMensal Churn  
0             Sim    ChequeDigital        29.85   Nao  
1             Nao      ChequePapel        56.95   Nao  
2             Sim      ChequePapel        53.85   Sim  
3             Nao    DebitoEmConta        42.30   Nao  
4             Sim    ChequeDigital        70.70   Sim

In [27]:
replace_bool_dict = { 'Sim': 1, 'Nao': 0 }

modified_data = data[['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn']].replace(replace_bool_dict)
modified_data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn
0        1            0             0                1      0
1        0            0             1                0      0
2        0            0             1                1      1
3        0            0             0                0      0
4        0            0             1                1      1

In [28]:
dummie_data = pd.get_dummies(data.drop(['Conjuge', 'Dependentes', 'TelefoneFixo', 'PagamentoOnline', 'Churn'], axis=1))
data = pd.concat([modified_data, dummie_data], axis=1)

pd.set_option('display.max_columns', 39)
data.head()

Conjuge  Dependentes  TelefoneFixo  PagamentoOnline  Churn  Maior65Anos  \
0        1            0             0                1      0            0   
1        0            0             1                0      0            0   
2        0            0             1                1      1            0   
3        0            0             0                0      0            0   
4        0            0             1                1      1            0   

   MesesDeContrato  ContaMensal  VariasLinhasTelefonicas_Nao  \
0                1        29.85                            0   
1               34        56.95                            1   
2                2        53.85                            1   
3               45        42.30                            0   
4                2        70.70                            1   

   VariasLinhasTelefonicas_SemServicoTelefonico  VariasLinhasTelefonicas_Sim  \
0                                             1                            0   
1                                             0                            0   
2                                             0                            0   
3                                             1                            0   
4                                             0                            0   

   ServicoDeInternet_DSL  ServicoDeInternet_FibraOptica  \
0                      1                              0   
1                      1                              0   
2                      1                              0   
3                      1                              0   
4                      0                              1   

   ServicoDeInternet_Nao  SegurancaOnline_Nao  \
0                      0                    1   
1                      0                    0   
2                      0                    0   
3                      0                    0   
4                      0                    1   

   SegurancaOnline_SemServicoDeInternet  SegurancaOnline_Sim  \
0                                     0                    0   
1                                     0                    1   
2                                     0                    1   
3                                     0                    1   
4                                     0                    0   

   BackupOnline_Nao  BackupOnline_SemServicoDeInternet  BackupOnline_Sim  \
0                 0                                  0                 1   
1                 1                                  0                 0   
2                 0                                  0                 1   
3                 1                                  0                 0   
4                 1                                  0                 0   

   SeguroNoDispositivo_Nao  SeguroNoDispositivo_SemServicoDeInternet  \
0                        1                                         0   
1                        0                                         0   
2                        1                                         0   
3                        0                                         0   
4                        1                                         0   

   SeguroNoDispositivo_Sim  SuporteTecnico_Nao  \
0                        0                   1   
1                        1                   1   
2                        0                   1   
3                        1                   0   
4                        0                   1   

   SuporteTecnico_SemServicoDeInternet  SuporteTecnico_Sim  TVaCabo_Nao  \
0                                    0                   0            1   
1                                    0                   0            1   
2                                    0                   0            1   
3                                    0                   1            1   
4                                    0                   0         

<h4 style="color: #fff;">
    Classificação
</h4>

<p style="color: #b4b4bb;">
    Quando precisamos prever a qual categoria pertence uma determinada amostra, trata-se de um problema de classificação. Alguns exemplos que podemos citar são:
</p>

<ul style="color: #b4b4bb;">
    <li>Prever se um(a) determinado(a) paciente está com Covid.</li>
    <li>Se um(a) cliente está propenso(a) a desistir da compra.</li>
    <li>Se algum(a) usuário(a) web está propenso(a) a clicar em um anúncio.</li>
</ul>

<p style="color: #b4b4bb;">
    Nesses casos mencionados, a previsão se concentra em 0 ou 1 (Covid/não Covid, desistir/não desistir, clicar/não clicar) que é denominada de classificação binária, na qual existem somente duas classes. Há também casos em que a classificação se dá com mais duas classes, chamada de classificação multiclasse, como a filtragem dos e-mails em “principal”, “social”, “promoções”, “importantes” ou “fóruns”.
</p>

<p style="color: #b4b4bb;">
    Entre os algoritmos de classificação podemos citar:
</p>

<ul style="color: #b4b4bb;">
    <li>K-Nearest Neighbors (KNN)</li>
    <li>Support Vector Machine (SVM)</li>
    <li>Decision Tree Classifier</li>
    <li>Random Forest Classifier</li>
</ul>

<h4 style="color: #fff;">
    Regressão
</h4>

<p style="color: #b4b4bb;">
    Quando precisamos prever um valor numérico específico, isso indica que estamos lidando com um problema de regressão. Alguns exemplos desses problemas estão relacionados à previsão de:
</p>

<ul style="color: #b4b4bb;">
    <li>preços/custos futuros</li>
    <li>estoque</li>
    <li>receita futura</li>
</ul>

<p style="color: #b4b4bb;">
    Nessas situações, podemos utilizar algum modelo de regressão para realizar essas previsões e apresentar como resposta algum valor contínuo relacionado ao problema. Existem diferentes tipos de algoritmos de machine learning utilizados para resolver esse tipo de problema:
</p>

<ul style="color: #b4b4bb;">
    <li>Linear Regression;</li>
    <li>Random Forest Regressor;</li>
    <li>Support Vector Regression (SVR).</li>
</ul>

<p style="color: #b4b4bb;">
    Caso queira aprofundar e conhecer mais sobre algoritmos de regressão, deixamos aqui a indicação de dois cursos que abordam esse assunto:
</p>

<ul style="color: #b4b4bb;">
    <li>
        <a>
            Regressão Linear: Testando Relações e Prevendo Resultados;
        </a>
    </li>
    <li>
        <a>
            Regressão Linear: Técnicas Avançadas de Modelagem.
        </a>
    </li>
</ul>

<h4 style="color: #fff;">
    Como funciona o K-Nearest Neighbors (KNN)
</h4>

<ul style="color: #b4b4bb;">
    <li>Recebe as informações;</li>
    <li>Calcula as distâncias;</li>
    <li>Ordena da menor distância para a maior;</li>
    <li>Faz uma contagem de classes;</li>
    <li>Classifica a partir de K-vizinhos;</li>
    <li>Defini o dados;</li>
</ul>

<h4 style="color: #fff;">
    Dados do modelo
</h4>

<p style="color: #b4b4bb;">
    Separar o conjunto de dados em treino e teste é uma parte importante para conseguirmos medir o desempenho real de um modelo de machine learning. Essa etapa consiste em dedicar parte do conjunto de dados para treinar o modelo e uma outra parte para teste. Mas qual o motivo de fazer isso?
</p>

<p style="color: #b4b4bb;">
    Imagine que você vai fazer uma prova e o(a) professor(a) passa uma atividade de revisão antes para treinar em casa. Chegando na prova, você percebe que as questões são exatamente iguais à revisão passada pelo(a) professor(a). Como você já sabia as questões, tirou 10! Isso é exatamente o que acontece quando utilizamos os mesmos dados para treinar e testar.
</p>

<p style="color: #b4b4bb;">
    Como os dados são conhecidos pelo modelo, ele simplesmente vai acertar tudo (ou quase tudo) na etapa de teste, pois são os mesmos dados. Para resolver isso, dividimos o conjunto de dados em treino e teste, sendo este último para simular dados nunca antes vistos pelo modelo.
</p>

<h4 style="color: #fff;">
    Dados de treino
</h4>

<p style="color: #b4b4bb;">
Os dados de treino são aqueles utilizados para a criação e treinamento do modelo. Normalmente a maioria dos dados, cerca de 70%, são utilizados para treinamento.
</p>

<h4 style="color: #fff;">
Dados de teste
</h4>

<p style="color: #b4b4bb;">
Os dados de teste são utilizados para comprovar que o modelo realmente funciona. Eles não são utilizados no treinamento do modelo e normalmente representam 30% da totalidade dos dados.
</p>

<p style="color: #b4b4bb;">
Além disso, no momento de realizar a separação desses dados é importante que ela seja feita de forma aleatória, para garantirmos que não haverá nenhum padrão no momento de divisão dos dados. Assim, cada amostra terá a mesma probabilidade de ser selecionada.
</p>

In [29]:
x_mariah = [[0,0,1,1,0,0,39.90,1,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,1]]

In [30]:
from sklearn.preprocessing import StandardScaler

x = data.drop(['Churn'], axis=1)
y = data['Churn']

# Essa função serve para deixar os valores na mesma escala (É importante usar ela).
scaler = StandardScaler()

scaled_x = scaler.fit_transform(x)
scaled_x

array([[ 1.03453023, -0.65401193, -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       ...,
       [ 1.03453023,  1.5290241 , -3.05401039, ...,  1.40641839,
        -0.54480692, -0.5298852 ],
       [ 1.03453023, -0.65401193,  0.32743831, ..., -0.71102597,
         1.83551265, -0.5298852 ],
       [-0.96662231, -0.65401193,  0.32743831, ..., -0.71102597,
        -0.54480692,  1.88720123]])

In [31]:
scaled_x_mariah = scaler.transform(pd.DataFrame(x_mariah, columns=x.columns))
scaled_x_mariah

array([[-0.96662231, -0.65401193,  0.32743831,  0.8297975 , -0.43991649,
        -1.31816495, -0.82630172,  1.03806605, -0.32743831, -0.85417615,
        -0.72373975,  1.12910177, -0.52592737,  1.00669571, -0.52592737,
        -0.63393298, -0.88361972, -0.52592737,  1.3782406 ,  1.12942721,
         1.90140322, -0.72396752, -0.98632101,  1.90140322, -0.63943864,
         1.2273572 , -0.52592737, -0.79013171, -0.80874158, -0.52592737,
         1.25617071, -0.56297505, -1.1059698 ,  1.94458183, -0.52504733,
        -0.71102597, -0.54480692,  1.88720123]])

<h4 style="color: #fff;">
    Distância Euclidiana
</h4>

In [32]:
import numpy as np

a = scaled_x_mariah
b = scaled_x[0]

square = np.square(a - b)
sum = np.sum(square)

distance = np.sqrt(sum)

<h4 style="color: #fff;">
    Implementação do modelo KNN
</h4>

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

train_x, test_x, train_y, test_y = train_test_split(scaled_x, y, test_size=.3, random_state=123)

knn_model = KNeighborsClassifier(metric='euclidean')
knn_model.fit(train_x, train_y)

knn_predictions = knn_model.predict(test_x)
knn_predictions

c:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

<h4 style="color: #fff;">
    Implementação do modelo Naive Base
</h4>

In [34]:
from sklearn.naive_bayes import BernoulliNB

median = np.median(train_x)

bnb_model = BernoulliNB(binarize=median)
bnb_model.fit(train_x, train_y)

bnb_predictions = bnb_model.predict(test_x)
bnb_predictions

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

<h4 style="color: #fff;">
    Implementação do modelo Decision Tree Classifier
</h4>

In [35]:
from sklearn.tree import DecisionTreeClassifier

dtc_model = DecisionTreeClassifier(criterion='entropy', random_state=42)
dtc_model.fit(train_x, train_y)

dtc_predictions = dtc_model.predict(test_x)
dtc_predictions


array([1, 0, 0, ..., 1, 0, 0], dtype=int64)

<h4 style="color: #fff;">
    Matriz de confusão
</h4>

<img src="./confusion_matrix.png" alt="confusion_matrix" style="background-color: #fff;" />

In [36]:
from sklearn.metrics import confusion_matrix

knn_confusion_matrix = confusion_matrix(test_y, knn_predictions)
bnb_confusion_matrix = confusion_matrix(test_y, bnb_predictions)
dtc_confusion_matrix = confusion_matrix(test_y, dtc_predictions)

print('Matrix KNN: ', knn_confusion_matrix)
print('Matrix Bernoulli Naive Base: ', bnb_confusion_matrix)
print('Matrix Decision Tree Classifier: ', dtc_confusion_matrix)

Matrix KNN:  [[1302  221]
 [ 317  273]]
Matrix Bernoulli Naive Base:  [[1051  472]
 [ 116  474]]
Matrix Decision Tree Classifier:  [[1249  274]
 [ 290  300]]


<h4 style="color: #fff;">
    Acurácia
</h4>

In [37]:
from sklearn.metrics import accuracy_score

knn_accuracy = accuracy_score(test_y, knn_predictions)
bnb_accuracy = accuracy_score(test_y, bnb_predictions)
dtc_accuracy = accuracy_score(test_y, dtc_predictions)

print('Accuracy KNN: ', knn_accuracy)
print('Accuracy Bernoulli Naive Base: ', bnb_accuracy)
print('Accuracy Decision Tree Classifier: ', dtc_accuracy)

Accuracy KNN:  0.7453857075248462
Accuracy Bernoulli Naive Base:  0.7217226691907241
Accuracy Decision Tree Classifier:  0.7330809275911027


<h4 style="color: #fff;">
    Precisão
</h4>

In [38]:
from sklearn.metrics import precision_score

knn_precision = precision_score(test_y, knn_predictions)
bnb_precision = precision_score(test_y, bnb_predictions)
dtc_precision = precision_score(test_y, dtc_predictions)

print('Precision KNN: ', knn_precision)
print('Precision Bernoulli Naive Base: ', bnb_precision)
print('Precision Decision Tree Classifier: ', dtc_precision)

Precision KNN:  0.5526315789473685
Precision Bernoulli Naive Base:  0.5010570824524313
Precision Decision Tree Classifier:  0.5226480836236934


<h4 style="color: #fff;">
    Recall
</h4>

<p style="color: #b4b4bb;">
    Outra métrica importante é a Recall ou revocação ou ainda sensibilidade, que calcula o quão bom o modelo está para classificar corretamente um resultado positivo.
</p>

In [39]:
from sklearn.metrics import recall_score

knn_recall = recall_score(test_y, knn_predictions)
bnb_recall = recall_score(test_y, bnb_predictions)
dtc_recall = recall_score(test_y, dtc_predictions)

print('Recall KNN: ', knn_recall)
print('Recall Bernoulli Naive Base: ', bnb_recall)
print('Recall Decision Tree Classifier: ', dtc_recall)

Recall KNN:  0.46271186440677964
Recall Bernoulli Naive Base:  0.8033898305084746
Recall Decision Tree Classifier:  0.5084745762711864


<p style="color: #b4b4bb;">
    Agora depende do analista decidir qual métrica ele usará para apresentar as pessoas.
</p>